# Generated by Django 6.0.5 on 2026-05-12 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_processo_homologacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprestador',
            name='documento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_substitutos', to='core.documentoprestador'),
        ),
        migrations.AddField(
            model_name='documentoprestador',
            name='motivo_reprovacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoprestador',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoprestador',
            name='status',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('EM_VALIDACAO', 'Em validacao'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('SUBSTITUIDO', 'Substituido')], default='ENVIADO', max_length=20),
        ),
        migrations.AddField(
            model_name='documentoprestador',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoprestador',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoprestador',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
