# Generated by Django 6.0.5 on 2026-05-26 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def create_fluxos_for_existing_processos(apps, schema_editor):
    User = apps.get_model('core', 'User')
    ProcessoHomologacao = apps.get_model('core', 'ProcessoHomologacao')
    FluxoAprovacao = apps.get_model('core', 'FluxoAprovacao')
    EtapaAprovacao = apps.get_model('core', 'EtapaAprovacao')
    HistoricoProcesso = apps.get_model('core', 'HistoricoProcesso')

    aprovadores = list(
        User.objects.filter(
            perfil='EQUIPE_ADMINISTRATIVA',
            is_active=True,
        ).order_by('id')
    )

    for processo in ProcessoHomologacao.objects.filter(status='EM_APROVACAO_INTERNA'):
        fluxo, created = FluxoAprovacao.objects.get_or_create(processo=processo)
        if fluxo.etapas.exists():
            continue

        agora = timezone.now()
        for index, aprovador in enumerate(aprovadores, start=1):
            EtapaAprovacao.objects.create(
                fluxo=fluxo,
                aprovador=aprovador,
                ordem=index,
                status='LIBERADO' if index == 1 else 'AGUARDANDO',
                data_liberacao=agora if index == 1 else None,
            )

        if created:
            HistoricoProcesso.objects.create(
                processo=processo,
                acao='Fluxo de aprovacao criado',
                descricao='Fluxo de aprovacao interna criado automaticamente durante migracao.',
                metadados={'total_aprovadores': len(aprovadores)},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documentoprestador_documento_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_aprovacao', to='core.processohomologacao')),
            ],
            options={
                'verbose_name': 'Fluxo de Aprovacao',
                'verbose_name_plural': 'Fluxos de Aprovacao',
                'ordering': ('-iniciado_em',),
            },
        ),
        migrations.CreateModel(
            name='EtapaAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('LIBERADO', 'Liberado'), ('CONCLUIDO', 'Concluido')], default='AGUARDANDO', max_length=20)),
                ('data_liberacao', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_aprovacao', to=settings.AUTH_USER_MODEL)),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.fluxoaprovacao')),
            ],
            options={
                'verbose_name': 'Etapa de Aprovacao',
                'verbose_name_plural': 'Etapas de Aprovacao',
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='ParecerProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('docusign_envelope_id', models.CharField(blank=True, max_length=255, null=True)),
                ('docusign_recipient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('docusign_status', models.CharField(blank=True, max_length=100, null=True)),
                ('docusign_assinado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_emitidos', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parecer', to='core.etapaaprovacao')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='core.processohomologacao')),
            ],
            options={
                'verbose_name': 'Parecer do Processo',
                'verbose_name_plural': 'Pareceres dos Processos',
                'ordering': ('data_hora',),
            },
        ),
        migrations.AddConstraint(
            model_name='etapaaprovacao',
            constraint=models.UniqueConstraint(fields=('fluxo', 'ordem'), name='unique_ordem_por_fluxo'),
        ),
        migrations.AddConstraint(
            model_name='etapaaprovacao',
            constraint=models.UniqueConstraint(fields=('fluxo', 'aprovador'), name='unique_aprovador_por_fluxo'),
        ),
        migrations.RunPython(create_fluxos_for_existing_processos, migrations.RunPython.noop),
    ]
