# Generated by Django 6.0.5 on 2026-05-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fluxoaprovacao_etapaaprovacao_parecerprocesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoaprovacao',
            name='encerrado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxoaprovacao',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluido'), ('ENCERRADO', 'Encerrado')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
