# Generated by Django 6.0.5 on 2026-05-27 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fluxoaprovacao_encerrado_em_fluxoaprovacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFluxoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao de Fluxo Padrao',
                'verbose_name_plural': 'Configuracoes de Fluxo Padrao',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='EtapaConfiguracaoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_configuracao_padrao', to=settings.AUTH_USER_MODEL)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.configuracaofluxopadrao')),
            ],
            options={
                'verbose_name': 'Etapa de Configuracao Padrao',
                'verbose_name_plural': 'Etapas de Configuracao Padrao',
                'ordering': ('ordem',),
                'constraints': [models.UniqueConstraint(fields=('configuracao', 'ordem'), name='unique_ordem_por_configuracao_fluxo'), models.UniqueConstraint(fields=('configuracao', 'aprovador'), name='unique_aprovador_por_configuracao_fluxo')],
            },
        ),
    ]
