# Generated by Django 6.0.5 on 2026-06-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracaofluxopadrao_etapaconfiguracaopadrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('conteudo_html', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('template_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proximas_versoes', to='core.templatecontrato')),
            ],
            options={
                'verbose_name': 'Template de Contrato',
                'verbose_name_plural': 'Templates de Contrato',
                'ordering': ('-ativo', '-versao', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='MinutaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(upload_to='minutas/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minuta_contrato', to='core.processohomologacao')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minutas', to='core.templatecontrato')),
            ],
            options={
                'verbose_name': 'Minuta de Contrato',
                'verbose_name_plural': 'Minutas de Contrato',
                'ordering': ('-gerado_em',),
            },
        ),
    ]
